window.APP_CONFIG = {
  SUPABASE_URL: "https://govdpkbkeyjlyfikjalp.supabase.co",
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvdmRwa2JrZXlqbHlmaWtqYWxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5OTgxMjcsImV4cCI6MjA4NTU3NDEyN30.jPI0iVp2Un_TTNusPmNKtZthfJ2rqpxydoUofzaI_Rs"
};
